export enum FLAT {
    "DIRECCIÓN GENERAL" = 2,
    "SECRETARIA GENERAL" = 2,
    "OFICINA JURÍDICA" = 2,
    "OFICINA CONTROL INTERNO" = 2,
    "ASESOR DIRECCIÓN GENERAL" = 2,
    "OFICINA DE SISTEMAS Y TICS" = 2,
    "SUBDIRECCIÓN GENERAL ÁREA DE PLANEACIÓN" = 2,
    "SUBDIRECCIÓN GENERAL ÁREA DE GESTIÓN AMBIENTAL" = 2,
    "SUBDIRECCIÓN GENERAL ÁREA ADMINISTRATIVA Y FINANCIERA" = 1,
    "GESTIÓN FINANCIERA" = 1,
    "CONTABILIDAD" = 1,
    "TESORERIA" = 1,
    "PAGADURIA" = 1,
    "VENTANILLA ÚNICA" = 1
}