export { default as Login } from './login'
export { default as Home } from './home'
export { default as Loader } from './loader'
export { default as User } from './user'
export { default as Equipment } from './equipment'
export { default as Maintenance } from './maintenance'
